plugins {
	id 'java'
	id 'maven-publish'
}


// Basic information
version = "1.0.0.A1"
group = "org.example.examplemodule"

ext.modulePackage = "org.example.examplemodule"
ext.moduleClass = "ExampleModule"
ext.authorname = "AerialWorks Software Foundation"

// Internal
apply plugin: 'eclipse'

Calendar cal = new GregorianCalendar();
cal.setTime(new Date());
ext.buildyear = cal.get(Calendar.YEAR).toString();

repositories {
	mavenCentral()
    flatDir {
        dirs 'deps/centuria-server/fluid'
	}
}

jar {
	manifest {
		attributes([
			"Specification-Title": project.name,
			"Specification-Vendor": "${authorname}",
			"Specification-Version": project.version,
			"Implementation-Title": project.name,
			"Implementation-Version": project.version,
			"Implementation-Vendor" :"${authorname}",
			"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
	includeEmptyDirs = false
}

dependencies {
	implementation project(":Centuria Legacy")
	implementation project(":connective-http")
	testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}

project.configurations.implementation.canBeResolved = true

task moduledata () {
	doLast {
		for (ResolvedArtifact arti : project.configurations.implementation.resolvedConfiguration.getResolvedArtifacts()) {
			if (arti.getClassifier() != null)
				continue;
			
		    String outFileNm = arti.name + (arti.getClassifier() != null && !arti.getClassifier().isEmpty() ? "-" + arti.getClassifier() : "")
		    if (outFileNm.equals("Centuria") || outFileNm.equals("centuria") || project("Centuria Legacy").configurations.implementation.resolvedConfiguration.getResolvedArtifacts().stream().anyMatch { t -> compareArtifacts(t, arti)})
		    	continue;
			copy {			    
				from arti.file
				rename arti.file.getName(), outFileNm + "." + arti.getExtension()
				into "build/gradleout/moduledata/libs"
			}
		}
		for (def task : project.tasks) {
			if (task instanceof AbstractArchiveTask) {
				if (!task.getArchiveClassifier().get().isEmpty())
					continue;
					
				copy {
					from task.getArchiveFile().get()
					rename task.getArchiveFile().get().getAsFile().getName(), task.getArchiveBaseName().get() + (task.getArchiveClassifier().get() != null && !task.getArchiveClassifier().get().isEmpty() ? "-" + task.getArchiveClassifier().get() : "") + "." + task.getArchiveExtension().get()
					into "build/gradleout/moduledata/modules"
				}
			}
		}
	}
}

boolean compareArtifacts(ResolvedArtifact arti, ResolvedArtifact t) {
	if (!arti.name.equals(t.name))
		return false;
	if (arti.getClassifier() != null && t.getClassifier() == null || arti.getClassifier() == null && t.getClassifier() != null)
		return false;
	if (!arti.getClassifier().equals(t.getClassifier()))
		return false;
	if (arti.getModuleVersion() != null && t.getModuleVersion() == null || arti.getModuleVersion() == null && t.getModuleVersion() != null)
		return false;
	if (arti.getModuleVersion() != null) {
		if (arti.getModuleVersion().getId() != null && t.getModuleVersion().getId() == null || arti.getModuleVersion().getId() == null && t.getModuleVersion().getId() != null)
			return false;
		if (arti.getModuleVersion().getId() != null) {
			var v1 = arti.getModuleVersion().getId()
			var v2 = t.getModuleVersion().getId()
			if (v1.getGroup() != null && v2.getGroup() == null || v1.getGroup() == null && v2.getGroup() != null)
				return false;
			if (!v1.getGroup().equals(v2.getGroup()))
				return false;
			if (v1.getName() != null && v2.getName() == null || v1.getName() == null && v2.getName() != null)
				return false;
			if (!v1.getName().equals(v2.getName()))
				return false;
			if (v1.getName() != null && v2.getName() == null || v1.getName() == null && v2.getName() != null)
				return false;
			if (!v1.getVersion().equals(v2.getVersion()))
				return false;
		}
	}
	return true;
}

moduledata.dependsOn project.tasks.build
build.finalizedBy moduledata
