name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create dependency folder
      run: mkdir deps
    - name: Download connective
      run: git clone https://github.com/SkySwimmer/connective-http deps/connective-http
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Publish build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Centuria Server
        path: build/Installations
